### ISSUE TITLE
counter para número de congresistas autores de proyecto de ley

### ISSUE THREAD

**Issue by aniversarioperu** [proyectosdeley/proyectos_de_ley#10]

**Comment by aniversarioperu** [comment]
se me ocurrió agregar un *badge* con el número de autores de cada proyecto. @MZunigaP @morachimo  Qué opinan? creo que en mi mente se veía mejor :-S

![a](https://cloud.githubusercontent.com/assets/5254076/5933242/24547b7c-a6c6-11e4-83af-c9aac5542afc.png)

**Comment by morachimo** [comment]
Yo lo veo bien. Un par de veces me he visto en la situación de contar esos nombres.

**Comment by aniversarioperu** [comment]
ok! cerrado con *commit* 3063e5565784de908243ad7577317a8e44922f8c

**Comment by aniversarioperu** [comment]
solo faltaría aprovar #8
