### ISSUE TITLE
Como puedo generar uno propio?

### ISSUE THREAD

**Issue by johnfelipe** [proyectosdeley/proyectos_de_ley#43]
Como puedo generar uno propio?
Gracias
Quedo atento

**Comment by aniversarioperu** [comment]
las instrucciones estan en el README https://github.com/proyectosdeley/proyectos_de_ley#configuraci%C3%B3n

pero este software está customizado para trabajar con los proyectos de ley que genera el Congreso Peruano. Quizá se necesite modificar para que funcione con las leyes de congresos de otros paises.
