### ISSUE TITLE
API que recibe codigo de proyecto de ley debe evitar devolver paginas 404

### ISSUE THREAD

**Issue by aniversarioperu** [proyectosdeley/proyectos_de_ley#52]
el codigo se está captando con [0-9]+\\-[0-9]+
hay que cambiar a .+
para que se emita exception DoesNotExist, entonces se devolverá al usuario:
"error": "proyecto no existe"

**Comment by carlosp420** [comment]
corregido en 5cbb8d4ca26bbcb73577707fa8821436659c86e6
