### ISSUE TITLE
estadísticas

### ISSUE THREAD

**Issue by aniversarioperu** [proyectosdeley/proyectos_de_ley#7]
Se habla de 4,095 proyectos pero no se explica qué ámbito de tiempo abarcan. Es esta legislatura 2011-2016 asumo no? Hay que precisarlo.

**Comment by aniversarioperu** [comment]
qué tal si se pone la aclaración en el título de la página?

![a](https://cloud.githubusercontent.com/assets/5254076/5792808/60fd26d6-9f33-11e4-856a-e0135d817a97.png)

**Comment by MZunigaP** [comment]
Está bien la propuesta! Pero dejémoslo así: 

Situación de los proyectos de Ley (Legislatura 2011-2016)

**Comment by aniversarioperu** [comment]
qué tal así?

![a](https://cloud.githubusercontent.com/assets/5254076/5909097/fcc8cf24-a5b5-11e4-8d11-1644c12aefa6.png)

**Comment by MZunigaP** [comment]
Mejor! Así me gusta más? Qué dice Miki?

**Comment by aniversarioperu** [comment]
quizá funcione si invocamos a Miguel via la cuenta de @hiperderecho

**Comment by MZunigaP** [comment]
Sí, justo lo copié! 

Le voy a pasar la voz por DM también! 

Oye, emitiste tu recibo??

**Comment by aniversarioperu** [comment]
ya, envía el cheque nomaaaaaaaaá

**Comment by morachimo** [comment]
Me parece que está perfecto.

**Comment by MZunigaP** [comment]
Miki y pudiste ver el texto de la presentación?

Disculpa por no responder un buen tiempo y ahora apurar. Fernando la quiere
lista ASAP para hacer un poco de campaña!

Abrazo!

On Tuesday, January 27, 2015, Miguel <notifications@github.com> wrote:

> Me parece que está perfecto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proyectosdeley/proyectos_de_ley/issues/7#issuecomment-71653187>
> .
>


-- 
Mario Zúñiga
m: mzunigap@gmail.com
t: @MZunigaP
p: +1 (202) 805 - 7886

Sent from mobile

**Comment by aniversarioperu** [comment]
queda entonces, este *issue* fue cerrado con el *commit* fa7982a380a4ef784cc4a9454b8de3b7cd3b0d87

**Comment by MZunigaP** [comment]
Ya está todo? 

Todavía me gustaría, si se puede, que en la primera página: 

1) Se vea (puede ser en una barra lateral) algo del “Sobre esta página”, como para que se vea de frente… la idea es que al toque la gente capte la idea de por qué le conviene usar nuestra página y no la página del Congreso.

2) La fecha de cada PL? 

Si no es muy complicado… 

Gracias!!

Mario

**Comment by aniversarioperu** [comment]
te refieres a ponerle la fecha de creación de cada proyecto? algo así?
![a](https://cloud.githubusercontent.com/assets/5254076/6009853/63a7b3ce-ab36-11e4-8fb6-231272ba29d2.png)

**Comment by MZunigaP** [comment]
Mesmamente!!

Y, creo que también al costado de Proyectos recientes debe decir: (Legislatura 2011-2016). 

Mil disculpas por pasar los cambios con gotera.. 

Gracias!

Mario

**Comment by aniversarioperu** [comment]
y si le pongo fechas relativas? tipo twitter? que dicen?

![a](https://cloud.githubusercontent.com/assets/5254076/6044055/85c70db0-ac99-11e4-8753-0f19e22b13e9.png)

**Comment by MZunigaP** [comment]
Personalmente prefiero fecha exacta, pero no sé, qué dices Miki… de repente eso es mejor…

**Comment by hiperderecho** [comment]
Voto por fecha exacta

**Comment by aniversarioperu** [comment]
qué tal fecha exacta, pero humana? 

![a](https://cloud.githubusercontent.com/assets/5254076/6044293/f92b8654-ac9a-11e4-9055-4c2fb4cf62b4.png)

**Comment by MZunigaP** [comment]
jajaja ok!

**Comment by aniversarioperu** [comment]
ya subí los cambios al servidor. http://www.proyectosdeley.pe/

también corregí otras fechas para que se lean en español (antes estaban en inglés).

**Comment by MZunigaP** [comment]
Gracias!!

On Wednesday, February 4, 2015, AniversarioPeru <notifications@github.com>
wrote:

> ya subí los cambios al servidor. http://www.proyectosdeley.pe/
>
> también corregí otras fechas para que se lean en español (antes estaban en
> inglés).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proyectosdeley/proyectos_de_ley/issues/7#issuecomment-72902550>
> .
>


-- 
Mario Zúñiga
m: mzunigap@gmail.com
t: @MZunigaP
p: +1 (202) 805 - 7886

Sent from mobile

**Comment by aniversarioperu** [comment]
cerrado con b8d9315e0014430eccdf4462bfaf657ef5a10ef4
