### ISSUE TITLE
destacar página estadísticas

### ISSUE THREAD

**Issue by aniversarioperu** [proyectosdeley/proyectos_de_ley#8]
parece que ese espacio fuera de visitas a la web proyectosdeley. Debería estar en un lugar más destacado.

**Comment by aniversarioperu** [comment]
Y si se pone en la página principal, y que al hacer click sobre esos números te lleven a la página <http://www.proyectosdeley.pe/stats/> para ver más detalles?

![a](https://cloud.githubusercontent.com/assets/5254076/5792874/7006f038-9f35-11e4-9fc8-131c9b3766d6.png)

**Comment by MZunigaP** [comment]
No sé si eso puede ir en la esquina derecha, quizá en otro color para que llame la atención y sí, abajo un llamado que diga: más detalles o "ver más". 

Pero ahorita tal como está parece el título de la página. Además, hay que dejar espacio para la explicación de la web (el texto que yo me comprometí a preparar, y que mando en breve).

**Comment by aniversarioperu** [comment]
qué tal ahí?

ver más es un link que lleva a la página de estadísticas:

![a](https://cloud.githubusercontent.com/assets/5254076/5910156/f5641144-a5bf-11e4-80fb-b4515070e416.png)

**Comment by MZunigaP** [comment]
Perfect!

**Comment by MZunigaP** [comment]
Guarda, pero esperemos a miki!!

**Comment by aniversarioperu** [comment]
ok!

**Comment by aniversarioperu** [comment]
cerrado con 46419177639cee4ac6a65b73d39242cbab58277f
